### ISSUE TITLE
Unrecognized options "naming_strategy, auto_mapping" under "doctrine.orm"

### ISSUE THREAD

**Issue by sterichards** [mapado/MysqlDoctrineFunctions#8]
This is the Symfony2 error I get, after the library installation, when adding the config and clearing the cache

**Comment by jdeniau** [comment]
IIRC with doctrine, you have 2 ways of configuring entity managers, one "helper" that makes only one entity manager available : 

```yaml
doctrine:
  orm:
    mappings: []
    auto_mapping: false
```

and the other one that is more verbose but supports multiple entity managers:
```yaml
doctrine:
  orm:
    entity_managers:
      some_em:
        mappings: []
        auto_mapping: false
```

Either you need to use the first syntax  with:
```yaml
doctrine:
    orm:
        dql:
            numeric_functions:
                rand:        Mapado\MysqlDoctrineFunctions\DQL\MysqlRand
                round:       Mapado\MysqlDoctrineFunctions\DQL\MysqlRound
            datetime_functions:
                date:        Mapado\MysqlDoctrineFunctions\DQL\MysqlDate
                date_format: Mapado\MysqlDoctrineFunctions\DQL\MysqlDateFormat
                # ... add all functions you need
```

or you need to switch to the verbose syntax
